"""Generate an exact Python lock from the verified local environment."""

from __future__ import annotations

from collections import deque
from importlib import metadata
from pathlib import Path

from packaging.requirements import Requirement


RUNTIME_ROOTS = {
    "fastapi": (),
    "uvicorn": ("standard",),
    "pydantic": (),
    "alembic": (),
    "sqlalchemy": (),
    "psycopg": ("binary",),
    "cryptography": (),
    "redis": (),
    "tiktoken": (),
    "mcp": (),
}
DEV_ROOTS = {**RUNTIME_ROOTS, "pytest": (), "httpx": ()}
BACKEND_ROOT = Path(__file__).resolve().parents[1] / "backend"


def main() -> None:
    """Resolve installed transitive dependencies and write stable pins."""
    _write_lock(
        roots=RUNTIME_ROOTS,
        output=BACKEND_ROOT / "requirements-runtime.lock",
    )
    _write_lock(
        roots=DEV_ROOTS,
        output=BACKEND_ROOT / "requirements.lock",
    )


def _write_lock(
    *,
    roots: dict[str, tuple[str, ...]],
    output: Path,
) -> None:
    """Write one dependency closure."""
    pending = deque(roots.items())
    resolved: dict[str, str] = {}
    while pending:
        name, extras = pending.popleft()
        distribution = metadata.distribution(name)
        canonical = distribution.metadata["Name"]
        key = canonical.casefold()
        if key in resolved:
            continue
        resolved[key] = f"{canonical}=={distribution.version}"
        for raw_requirement in distribution.requires or ():
            requirement = Requirement(raw_requirement)
            if not _included(requirement, extras):
                continue
            pending.append((requirement.name, tuple(requirement.extras)))
    lines = [
        "# Generated by scripts/lock_python_dependencies.py.",
        "# Regenerate from a clean Python 3.13 environment after dependency review.",
        *sorted(resolved.values(), key=str.casefold),
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def _included(requirement: Requirement, extras: tuple[str, ...]) -> bool:
    if requirement.marker is None:
        return True
    candidates = extras or ("",)
    return any(requirement.marker.evaluate({"extra": extra}) for extra in candidates)


if __name__ == "__main__":
    main()
